import React, { useMemo, useState } from 'react';
import C from '../../constants/theme';
import { Button, CardHeader, Input } from '../ui';

const card = { background: '#fff', borderRadius: 12, boxShadow: '0 1px 6px rgba(0,0,0,.07)', overflow: 'hidden' };

export default function DailyCommandCenter({ data, setData, navigate, dateContext }) {
  const [text, setText] = useState('');
  const today = dateContext.today;
  const items = (data.dailyPlan || []).filter((item) => item.date === today);
  const priorities = useMemo(() => { const review = (data.weeklyReviews || [])[0]; return review ? ['p1', 'p2', 'p3'].map((key) => review[key]).filter(Boolean) : []; }, [data.weeklyReviews]);
  const incompleteHabits = data.habits.defs.filter((habit) => !data.habits.logs[`${today}_${habit.id}`]).length;
  const add = () => { if (!text.trim()) return; setData((previous) => ({ ...previous, dailyPlan: [...(previous.dailyPlan || []), { id: Date.now(), date: today, text: text.trim(), done: false }] })); setText(''); };
  const toggle = (id) => setData((previous) => ({ ...previous, dailyPlan: (previous.dailyPlan || []).map((item) => item.id === id ? { ...item, done: !item.done } : item) }));
  const remove = (id) => setData((previous) => ({ ...previous, dailyPlan: (previous.dailyPlan || []).filter((item) => item.id !== id) }));
  return <div style={card}><CardHeader icon="🎯" title="DAILY COMMAND CENTER" color={C.navy2} right={<span style={{ color: 'rgba(255,255,255,.7)', fontSize: 10 }}>{today}</span>} /><div style={{ padding: 12, display: 'grid', gridTemplateColumns: '1.1fr 1fr .9fr', gap: 12 }}><div><div style={{ fontSize: 9, fontWeight: 800, color: C.g3, marginBottom: 6 }}>TODAY’S OUTCOMES</div>{items.map((item) => <div key={item.id} style={{ display: 'flex', gap: 6, alignItems: 'center', marginBottom: 5 }}><input aria-label={item.text} type="checkbox" checked={item.done} onChange={() => toggle(item.id)} /><span style={{ flex: 1, fontSize: 11, textDecoration: item.done ? 'line-through' : 'none', color: item.done ? C.g3 : C.dark }}>{item.text}</span><button onClick={() => remove(item.id)} style={{ border: 0, background: 'none', color: C.red, cursor: 'pointer' }}>×</button></div>)}{!items.length && <div style={{ fontSize: 10, color: C.g2 }}>Add the one to three outcomes that define a good day.</div>}<div style={{ display: 'flex', gap: 5, marginTop: 8 }}><Input value={text} onChange={(event) => setText(event.target.value)} placeholder="Add today’s outcome" /><Button onClick={add} color={C.navy2} small>Add</Button></div></div><div><div style={{ fontSize: 9, fontWeight: 800, color: C.g3, marginBottom: 6 }}>WEEKLY PRIORITIES</div>{priorities.length ? priorities.map((priority) => <div key={priority} style={{ fontSize: 10, padding: '5px 0', borderBottom: `1px solid ${C.g1}` }}>• {priority}</div>) : <div style={{ fontSize: 10, color: C.g2 }}>Complete a weekly review to set priorities.</div>}<Button onClick={() => navigate('review')} color={C.review} small outline>Open weekly review</Button></div><div><div style={{ fontSize: 9, fontWeight: 800, color: C.g3, marginBottom: 6 }}>QUICK STATUS</div><div style={{ fontSize: 11, marginBottom: 6 }}><b>{incompleteHabits}</b> habits still open</div><div style={{ display: 'flex', gap: 5, flexWrap: 'wrap' }}><Button onClick={() => navigate('habits')} color={C.teal} small outline>Habits</Button><Button onClick={() => navigate('timelog')} color={C.blue} small outline>Log time</Button><Button onClick={() => navigate('finance')} color={C.green} small outline>Spending</Button></div></div></div></div>;
}
